name: Windows build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install MinGW toolchain
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          mingw-w64-i686-gcc
          mingw-w64-i686-binutils
          make
    - name: Build
      shell: msys2 {0}
      run: make TARGET=KeyboardSim.exe
